# POST http://127.0.0.1:3000/peer HTTP/1.1
# content-type: application/json

# {
#     "username": "3",
#     "peerId": "1"
# }

# GET http://127.0.0.1:3000/user/3 HTTP/1.1
# content-type: application/json

# DELETE  http://127.0.0.1:3000/user/3 HTTP/1.1
# content-type: application/json

# GET http://127.0.0.1:3000/peer/1 HTTP/1.1
# content-type: application/json

# POST http://127.0.0.1:3000/peer/update HTTP/1.1
# content-type: application/json

# {
#     "username": "2",
#     "peerId": "4"
# }